apiVersion: v1
kind: Service
metadata:
  name: {{ include "omniroute.fullname" . }}
  labels:
    {{- include "omniroute.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "omniroute.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: live-ws
      port: {{ .Values.service.liveWsPort }}
      targetPort: live-ws
      protocol: TCP
