apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omniroute

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: pvc-storageclass.yaml
    target:
      kind: PersistentVolumeClaim
      name: omniroute-data
